var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,e){b!=Array.prototype&&b!=Object.prototype&&(b[d]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var d=0;return $jscomp.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,d){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var e=0,g={next:function(){if(e<b.length){var h=e++;return{value:d(h,b[h]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(b,d,e,g){if(d){e=$jscomp.global;b=b.split(".");for(g=0;g<b.length-1;g++){var h=b[g];h in e||(e[h]={});e=e[h]}b=b[b.length-1];g=e[b];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
(function(b,d){b.simpleStorage=d()})(this,function(){function b(){q=x();e();r();"addEventListener"in window?window.addEventListener("storage",d,!1):document.attachEvent("onstorage",d);"addEventListener"in window&&window.addEventListener("pageshow",function(a){a.persisted&&d()},!1);q=!0}function d(){try{e()}catch(a){q=!1;return}r()}function e(){var a=localStorage.getItem(m);try{c=JSON.parse(a)||{}}catch(k){c={}}u=h()}function g(){try{localStorage.setItem(m,JSON.stringify(c)),u=h()}catch(a){return n(a)}return!0}
function h(){var a=localStorage.getItem(m);return a?String(a).length:0}function r(){var a,b=Infinity,d=0;clearTimeout(t);if(c&&c.__simpleStorage_meta&&c.__simpleStorage_meta.TTL){var e=+new Date;var l=c.__simpleStorage_meta.TTL.keys||[];var f=c.__simpleStorage_meta.TTL.expire||{};var h=0;for(a=l.length;h<a;h++)if(f[l[h]]<=e)d++,delete c[l[h]],delete f[l[h]];else{f[l[h]]<b&&(b=f[l[h]]);break}Infinity!==b&&(t=setTimeout(r,Math.min(b-e,2147483647)));d&&(l.splice(0,d),w(),g())}}function v(a,b){var d=
+new Date,k,e=!1;b=Number(b)||0;if(0!==b)if(c.hasOwnProperty(a)){c.__simpleStorage_meta||(c.__simpleStorage_meta={});c.__simpleStorage_meta.TTL||(c.__simpleStorage_meta.TTL={expire:{},keys:[]});c.__simpleStorage_meta.TTL.expire[a]=d+b;if(c.__simpleStorage_meta.TTL.expire.hasOwnProperty(a)){var f=0;for(k=c.__simpleStorage_meta.TTL.keys.length;f<k;f++)c.__simpleStorage_meta.TTL.keys[f]===a&&c.__simpleStorage_meta.TTL.keys.splice(f)}f=0;for(k=c.__simpleStorage_meta.TTL.keys.length;f<k;f++)if(c.__simpleStorage_meta.TTL.expire[c.__simpleStorage_meta.TTL.keys[f]]>
d+b){c.__simpleStorage_meta.TTL.keys.splice(f,0,a);e=!0;break}e||c.__simpleStorage_meta.TTL.keys.push(a)}else return!1;else if(c&&c.__simpleStorage_meta&&c.__simpleStorage_meta.TTL){if(c.__simpleStorage_meta.TTL.expire.hasOwnProperty(a))for(delete c.__simpleStorage_meta.TTL.expire[a],f=0,k=c.__simpleStorage_meta.TTL.keys.length;f<k;f++)if(c.__simpleStorage_meta.TTL.keys[f]===a){c.__simpleStorage_meta.TTL.keys.splice(f,1);break}w()}clearTimeout(t);c&&c.__simpleStorage_meta&&c.__simpleStorage_meta.TTL&&
c.__simpleStorage_meta.TTL.keys.length&&(t=setTimeout(r,Math.min(Math.max(c.__simpleStorage_meta.TTL.expire[c.__simpleStorage_meta.TTL.keys[0]]-d,0),2147483647)));return!0}function w(){var a=!1,b=!1,d;if(!c||!c.__simpleStorage_meta)return a;c.__simpleStorage_meta.TTL&&!c.__simpleStorage_meta.TTL.keys.length&&(delete c.__simpleStorage_meta.TTL,a=!0);for(d in c.__simpleStorage_meta)if(c.__simpleStorage_meta.hasOwnProperty(d)){b=!0;break}b||(delete c.__simpleStorage_meta,a=!0);return a}function x(){var a=
0;if(null===window.localStorage||"unknown"===typeof window.localStorage)throw a=Error("localStorage is disabled"),a.code="LS_DISABLED",a;if(!window.localStorage)throw a=Error("localStorage not supported"),a.code="LS_NOT_AVAILABLE",a;try{a=window.localStorage.length}catch(k){throw n(k);}try{window.localStorage.setItem("__simpleStorageInitTest",(+new Date).toString(16)),window.localStorage.removeItem("__simpleStorageInitTest")}catch(k){if(a)throw n(k);a=Error("localStorage is disabled");a.code="LS_DISABLED";
throw a;}return!0}function n(a){if(22===a.code||1014===a.code||0<[-2147024882,-2146828281,-21474675259].indexOf(a.number))return a=Error("localStorage quota exceeded"),a.code="LS_QUOTA_EXCEEDED",a;if(18===a.code||1E3===a.code)return a=Error("localStorage is disabled"),a.code="LS_DISABLED",a;"TypeError"===a.name&&(a=Error("localStorage is disabled"),a.code="LS_DISABLED");return a}function z(a){if(!a)return p="OK",a;switch(a.code){case "LS_NOT_AVAILABLE":case "LS_DISABLED":case "LS_QUOTA_EXCEEDED":p=
a.code;break;default:p=a.code||a.number||a.message||a.name}return a}var m=void 0==window.hi5_storage_name?"simpleStorage":window.hi5_storage_name,c=!1,u=0,q=!1,t=null,p="OK";try{b()}catch(a){z(a)}return{version:"0.2.1",status:p,name:function(a){if(void 0!=a)m=a;else return m},canUse:function(){return"OK"===p&&!!q},set:function(a,b,d){if("__simpleStorage_meta"===a||!c)return!1;if("undefined"===typeof b)return this.deleteKey(a);d=d||{};try{b=JSON.parse(JSON.stringify(b))}catch(y){return n(y)}c[a]=b;
v(a,d.TTL||0);return g()},hasKey:function(a){return!!this.get(a)},get:function(a){if(!c)return!1;if(c.hasOwnProperty(a)&&"__simpleStorage_meta"!==a&&this.getTTL(a))return c[a]},deleteKey:function(a){return c?a in c?(delete c[a],v(a,0),g()):!1:!1},setTTL:function(a,b){if(!c)return!1;v(a,b);return g()},getTTL:function(a){return c?c.hasOwnProperty(a)?c.__simpleStorage_meta&&c.__simpleStorage_meta.TTL&&c.__simpleStorage_meta.TTL.expire&&c.__simpleStorage_meta.TTL.expire.hasOwnProperty(a)?(a=Math.max(c.__simpleStorage_meta.TTL.expire[a]-
+new Date||0,0))||!1:Infinity:!1:!1},flush:function(){if(!c)return!1;c={};try{return localStorage.removeItem(m),!0}catch(a){return n(a)}},index:function(){if(!c)return!1;var a=[],b;for(b in c)c.hasOwnProperty(b)&&"__simpleStorage_meta"!==b&&a.push(b);return a},storageSize:function(){return u}}});
