var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(c,e,d){if(null==c)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return c+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,d){c!=Array.prototype&&c!=Object.prototype&&(c[e]=d.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,e,d,h){if(e){d=$jscomp.global;c=c.split(".");for(h=0;h<c.length-1;h++){var p=c[h];p in d||(d[p]={});d=d[p]}c=c[c.length-1];h=d[c];e=e(h);e!=h&&null!=e&&$jscomp.defineProperty(d,c,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("String.prototype.repeat",function(c){return c?c:function(c){var d=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var e="";c;)if(c&1&&(e+=d),c>>>=1)d+=d;return e}},"es6","es3");
!function(){function c(e){var k=e;if(h[k])k=h[k];else{for(var l=k,f,q=[],a=0;l;){if(null!==(f=d.text.exec(l)))q.push(f[0]);else if(null!==(f=d.modulo.exec(l)))q.push("%");else if(null!==(f=d.placeholder.exec(l))){if(f[2]){a|=1;var m=[],g=f[2],b;if(null!==(b=d.key.exec(g)))for(m.push(b[1]);""!==(g=g.substring(b[0].length));)if(null!==(b=d.key_access.exec(g)))m.push(b[1]);else if(null!==(b=d.index_access.exec(g)))m.push(b[1]);else throw new SyntaxError("[sprintf] failed to parse named argument key");
else throw new SyntaxError("[sprintf] failed to parse named argument key");f[2]=m}else a|=2;if(3===a)throw Error("[sprintf] mixing positional and named placeholders is not (yet) supported");q.push(f)}else throw new SyntaxError("[sprintf] unexpected placeholder");l=l.substring(f[0].length)}k=h[k]=q}l=arguments;f=1;q=k.length;m="";var n,p;for(g=0;g<q;g++)if("string"===typeof k[g])m+=k[g];else if(Array.isArray(k[g])){b=k[g];if(b[2])for(a=l[f],n=0;n<b[2].length;n++){if(!a.hasOwnProperty(b[2][n]))throw Error(c('[sprintf] property "%s" does not exist',
b[2][n]));a=a[b[2][n]]}else a=b[1]?l[b[1]]:l[f++];d.not_type.test(b[8])&&d.not_primitive.test(b[8])&&a instanceof Function&&(a=a());if(d.numeric_arg.test(b[8])&&"number"!==typeof a&&isNaN(a))throw new TypeError(c("[sprintf] expecting number but found %T",a));d.number.test(b[8])&&(p=0<=a);switch(b[8]){case "b":a=parseInt(a,10).toString(2);break;case "c":a=String.fromCharCode(parseInt(a,10));break;case "d":case "i":a=parseInt(a,10);break;case "j":a=JSON.stringify(a,null,b[6]?parseInt(b[6]):0);break;
case "e":a=b[7]?parseFloat(a).toExponential(b[7]):parseFloat(a).toExponential();break;case "f":a=b[7]?parseFloat(a).toFixed(b[7]):parseFloat(a);break;case "g":a=b[7]?String(Number(a.toPrecision(b[7]))):parseFloat(a);break;case "o":a=(parseInt(a,10)>>>0).toString(8);break;case "s":a=String(a);a=b[7]?a.substring(0,b[7]):a;break;case "t":a=String(!!a);a=b[7]?a.substring(0,b[7]):a;break;case "T":a=Object.prototype.toString.call(a).slice(8,-1).toLowerCase();a=b[7]?a.substring(0,b[7]):a;break;case "u":a=
parseInt(a,10)>>>0;break;case "v":a=a.valueOf();a=b[7]?a.substring(0,b[7]):a;break;case "x":a=(parseInt(a,10)>>>0).toString(16);break;case "X":a=(parseInt(a,10)>>>0).toString(16).toUpperCase()}if(d.json.test(b[8]))m+=a;else{if(!d.number.test(b[8])||p&&!b[3])var t="";else t=p?"+":"-",a=a.toString().replace(d.sign,"");n=b[4]?"0"===b[4]?"0":b[4].charAt(1):" ";var r=b[6]-(t+a).length;r=b[6]?0<r?n.repeat(r):"":"";m+=b[5]?t+a+r:"0"===n?t+r+a:r+t+a}}return m}function e(d,e){return c.apply(null,[d].concat(e||
[]))}var d={not_string:/[^s]/,not_bool:/[^t]/,not_type:/[^T]/,not_primitive:/[^v]/,number:/[diefg]/,numeric_arg:/[bcdiefguxX]/,json:/[j]/,not_json:/[^j]/,text:/^[^\x25]+/,modulo:/^\x25{2}/,placeholder:/^\x25(?:([1-9]\d*)\$|\(([^\)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-gijostTuvxX])/,key:/^([a-z_][a-z_\d]*)/i,key_access:/^\.([a-z_][a-z_\d]*)/i,index_access:/^\[(\d+)\]/,sign:/^[\+\-]/},h=Object.create(null);"undefined"!==typeof exports&&(exports.sprintf=c,exports.vsprintf=e);"undefined"!==
typeof window&&(window.sprintf=c,window.vsprintf=e,"function"===typeof define&&define.amd&&define(function(){return{sprintf:c,vsprintf:e}}))}();
